authorName: default
experimentName: example_nni
trialConcurrency: 4
maxExecDuration: 100h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python experiment_nni.py
  codeDir: .
  gpuNum: 1
